seed: 2024
resume: true
device: 0
use_amp: true
num_folds: 5
folds: [0, 1, 2, 3, 4]
epochs: 20
model:
  name: RSNA2024AttentionNet
  timm_model:
    model_name: maxvit_nano_rw_256.sw_in1k
    pretrained: true
    features_only: false
    in_chans: 1
    drop_rate: 0.3
    drop_path_rate: 0.2
  loss:
    name: RSNA2024Loss
    ce_loss:
      name: CrossEntropyLoss
      weight: [1.0, 2.0, 4.0]
    conditions: [neural_foraminal_narrowing, subarticular_stenosis]
    condition_weight: [1.0, 1.0]
    levels: [any]
    sevear_loss: false
  num_degenerative_conditions: 2
  num_segments: 1
  num_classes: 3
  use_planes: [sagittal_t1, sagittal_t2, axial_t2]
optimizer:
  name: AdamW
  lr: 0.0000125
  weight_decay: 0.01
  betas:
    - 0.9
    - 0.999
scheduler:
  name: OneCycleLR
  max_lr: ${optimizer.lr}
  pct_start: 0.3
dataset:
  name: RSNA2024DatasetVer5
  image_root: tkmn/classification_datasets/v9
  label_csv_path: train_fold.csv
  image_csv_path: tkmn/classification_datasets/v9/train_images.csv

  image_shapes:
    "Sagittal T1": [256, 256, 15]
    "Sagittal T2/STIR": [256, 256, 15]
    "Axial T2": [256, 256, 10]
  target_levels: [L1/L2, L2/L3, L3/L4, L4/L5, L5/S1]
  target_sides: [left, right]
dataloader:
  batch_size: 4
  num_workers: 8
submit:
  base_submit_csv: null

use_tqdm: true  # tqdmを使用するかどうか

transform:
  "Sagittal T1":
    image_size: [256, 256]
    brightness_limit: [-0.12, 0.12]
    contrast_limit: [-0.12, 0.12]
    brightness_contrast_p: 0.7
    blur_limit: 5
    blur_p: 0.1
    noise_var_limit: [1.0, 5.0]
    distort_limit: 0.7
    grid_distort_limit: 0.7
    elastic_alpha: 2.0
    distortion_p: 0.7
    shift_limit: 0.1
    scale_limit: 0.1
    rotate_limit: 10
    shift_scale_rotate_p: 0.7
    max_holes: 14
    max_height: 35
    max_width: 35
    min_holes: 2
    min_height: 5
    min_width: 5
    coarse_dropout_p: 0.7
  "Sagittal T2/STIR":
    image_size: [256, 256]
    brightness_limit: [-0.12, 0.12]
    contrast_limit: [-0.12, 0.12]
    brightness_contrast_p: 0.7
    blur_limit: 5
    blur_p: 0.1
    noise_var_limit: [1.0, 5.0]
    distort_limit: 0.7
    grid_distort_limit: 0.7
    elastic_alpha: 2.0
    distortion_p: 0.7
    shift_limit: 0.1
    scale_limit: 0.1
    rotate_limit: 10
    shift_scale_rotate_p: 0.7
    max_holes: 14
    max_height: 35
    max_width: 35
    min_holes: 2
    min_height: 5
    min_width: 5
    coarse_dropout_p: 0.7
  "Axial T2":
    image_size: [256, 256]
    brightness_limit: [-0.12, 0.12]
    contrast_limit: [-0.12, 0.12]
    brightness_contrast_p: 0.7
    blur_limit: 5
    blur_p: 0.1
    noise_var_limit: [1.0, 5.0]
    distort_limit: 0.7
    grid_distort_limit: 0.7
    elastic_alpha: 2.0
    distortion_p: 0.7
    shift_limit: 0.1
    scale_limit: 0.1
    rotate_limit: 10
    shift_scale_rotate_p: 0.7
    max_holes: 14
    max_height: 35
    max_width: 35
    min_holes: 2
    min_height: 5
    min_width: 5
    coarse_dropout_p: 0.7