seed: 2024
resume: true
device: 0
use_amp: true
num_folds: 5
folds: [0, 1, 2, 3, 4]
epochs: 20
model:
  name: RSNA2024AttentionNet
  timm_model:
    model_name: efficientnetv2_rw_t.ra2_in1k
    pretrained: true
    features_only: false
    in_chans: 1
    drop_rate: 0.3
    drop_path_rate: 0.2
  loss:
    name: RSNA2024Loss
    ce_loss:
      name: CrossEntropyLoss
      weight: [1.0, 2.0, 4.0]
    conditions: [spinal_canal_stenosis, left_neural_foraminal_narrowing, right_neural_foraminal_narrowing, left_subarticular_stenosis, right_subarticular_stenosis]
    condition_weight: [1.0, 0.25, 0.25, 0.25, 0.25]
    levels: [any]
    sevear_loss: true
  num_degenerative_conditions: 5
  num_segments: 1
  num_classes: 3
  use_planes: [sagittal_t1, sagittal_t2, axial_t2]
optimizer:
  name: AdamW
  lr: 0.0000125
  weight_decay: 0.01
  betas:
    - 0.9
    - 0.999
scheduler:
  name: OneCycleLR
  max_lr: ${optimizer.lr}
  pct_start: 0.3
dataset:
  name: RSNA2024DatasetVer2
  image_root: tkmn/classification_datasets/v9
  label_csv_path: train_fold.csv
  image_csv_path: tkmn/classification_datasets/v9/train_images.csv
  image_shapes:
    "Sagittal T1": [224, 224, 15]
    "Sagittal T2/STIR": [224, 224, 15]
    "Axial T2": [224, 224, 10]
  target_levels: [L1/L2, L2/L3, L3/L4, L4/L5, L5/S1]
dataloader:
  batch_size: 3
  num_workers: 8
submit:
  base_submit_csv: null

use_tqdm: true  # tqdmを使用するかどうか

transform:
  "Sagittal T1":
    image_size: [224, 224]
    brightness_limit: [-0.18, 0.18]
    contrast_limit: [-0.18, 0.18]
    brightness_contrast_p: 0.55
    blur_limit: 7
    blur_p: 0.15
    noise_var_limit: [2.5, 9.0]
    distort_limit: 0.9
    grid_distort_limit: 0.9
    elastic_alpha: 2.0
    distortion_p: 0.75
    shift_limit: 0.1
    scale_limit: 0.1
    rotate_limit: 14
    shift_scale_rotate_p: 0.55
    max_holes: 12
    max_height: 32
    max_width: 32
    min_holes: 4
    min_height: 7
    min_width: 7
    coarse_dropout_p: 0.55
  "Sagittal T2/STIR":
    image_size: [224, 224]
    brightness_limit: [-0.18, 0.18]
    contrast_limit: [-0.18, 0.18]
    brightness_contrast_p: 0.55
    blur_limit: 7
    blur_p: 0.15
    noise_var_limit: [2.5, 9.0]
    distort_limit: 0.9
    grid_distort_limit: 0.9
    elastic_alpha: 2.0
    distortion_p: 0.75
    shift_limit: 0.1
    scale_limit: 0.1
    rotate_limit: 14
    shift_scale_rotate_p: 0.55
    max_holes: 12
    max_height: 32
    max_width: 32
    min_holes: 4
    min_height: 7
    min_width: 7
    coarse_dropout_p: 0.55
  "Axial T2":
    image_size: [224, 224]
    brightness_limit: [-0.18, 0.18]
    contrast_limit: [-0.18, 0.18]
    brightness_contrast_p: 0.55
    blur_limit: 7
    blur_p: 0.15
    noise_var_limit: [2.5, 9.0]
    distort_limit: 0.9
    grid_distort_limit: 0.9
    elastic_alpha: 2.0
    distortion_p: 0.75
    shift_limit: 0.1
    scale_limit: 0.1
    rotate_limit: 14
    shift_scale_rotate_p: 0.55
    max_holes: 12
    max_height: 32
    max_width: 32
    min_holes: 4
    min_height: 7
    min_width: 7
    coarse_dropout_p: 0.55