seed: 2024
resume: true
device: 0
use_amp: true
num_folds: 5
folds: [0, 1, 2, 3, 4]
epochs: 20
model:
  name: RSNA2024AttentionNet
  timm_model:
    model_name: tf_efficientnet_b3.ns_jft_in1k
    pretrained: true
    features_only: false
    in_chans: 1
    drop_rate: 0.3
    drop_path_rate: 0.2
  loss:
    name: RSNA2024Loss
    ce_loss:
      name: CrossEntropyLoss
      weight: [1.0, 2.0, 4.0]
    conditions: [neural_foraminal_narrowing, subarticular_stenosis]
    condition_weight: [1.0, 1.0]
    levels: [any]
    overall_loss_weight: 1.0
    level_loss_weight: 0.0
    slice_loss_weight: 0.0
  num_degenerative_conditions: 2
  num_segments: 1
  num_classes: 3
  use_planes: [sagittal_t1, sagittal_t2, axial_t2]
optimizer:
  name: AdamW
  lr: 0.0000125
  weight_decay: 0.01
  betas:
    - 0.9
    - 0.999
scheduler:
  name: OneCycleLR
  max_lr: ${optimizer.lr}
  pct_start: 0.3
dataset:
  name: RSNA2024DatasetVer5
  image_root: moyashii/classification_datasets/v9
  label_csv_path: train_fold.csv
  image_csv_path: moyashii/classification_datasets/v9/train_images.csv
  coord_csv_path: rsna-2024-lumbar-spine-degenerative-classification/train_label_coordinates.csv
  image_shapes:
    "Sagittal T1": [224, 224, 15]
    "Sagittal T2/STIR": [224, 224, 15]
    "Axial T2": [224, 224, 10]
  target_levels: [L1/L2, L2/L3, L3/L4, L4/L5, L5/S1]
  target_sides: [left, right]
transform:
  "Sagittal T1":
    image_size: [224, 224]
  "Sagittal T2/STIR":
    image_size: [224, 224]
  "Axial T2":
    image_size: [224, 224]
dataloader:
  batch_size: 4
  num_workers: 8
metrics:
  train_csv_path: rsna-2024-lumbar-spine-degenerative-classification/train.csv
submit:
  base_submit_csv: null
